### ISSUE TITLE
Module '"zulip-js"' has no exported member 'type'

### ISSUE THREAD

**Issue by sutidor** [ornicar/zulip-remind#13]
Hi,
I am trying to run the docker version:
```
yarn run v1.22.19

$ nodemon --watch 'src/**/*.ts' --exec ts-node src/index.ts

[nodemon] 2.0.7

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): src/**/*.ts

[nodemon] watching extensions: ts,json

[nodemon] starting `ts-node src/index.ts`

/var/reminder-bot/node_modules/ts-node/src/index.ts:587

    return new TSError(diagnosticText, diagnosticCodes);
TSError: ⨯ Unable to compile TypeScript:

src/index.ts(1,21): error TS2614: Module '"zulip-js"' has no exported member 'type'. Did you mean to use 'import type from "zulip-js"' instead?

src/index.ts(1,26): error TS1005: ',' expected.

    at createTSError (/var/reminder-bot/node_modules/ts-node/src/index.ts:587:12)

    at reportTSError (/var/reminder-bot/node_modules/ts-node/src/index.ts:591:19)

    at getOutput (/var/reminder-bot/node_modules/ts-node/src/index.ts:921:36)

    at Object.compile (/var/reminder-bot/node_modules/ts-node/src/index.ts:1189:32)

    at Module.m._compile (/var/reminder-bot/node_modules/ts-node/src/index.ts:1295:42)

    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)

    at Object.require.extensions.(anonymous function) [as .ts] (/var/reminder-bot/node_modules/ts-node/src/index.ts:1298:12)

    at Module.load (internal/modules/cjs/loader.js:653:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[nodemon] app crashed - waiting for file changes before starting...

```

secondly, in the docker compose there is no `volumes:` defined. How is this supposed to work?

**Comment by sutidor** [comment]
Appreciated 🙏Please merge if you can @ornicar
